url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kelay | Software Engineer" # the name of your site, e.g. ACME Corp.
repository: kelaynodalo/kelaynodalo.github.io

plugins:
  - jekyll-postcss
  - "jekyll-github-metadata"
  - jemoji
